export const COCKTAILS_DATA = [
  {
    id: 'd38238ec-d26b-4cc0-a3c5-9a00fbc34d58',
    name: 'A Quiet Cocktail',
    description: 'Inspired by the 2018 film A Quiet Place.',
    img: 'https://images.unsplash.com/photo-1609951651556-5334e2706168?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Triple Sec Orange Liqueur', quantity: '20 ml' },
      { name: 'Dry vermouth', quantity: '20 ml' },
      { name: 'Sweet vermouth', quantity: '20 ml' },
      { name: 'Gin', quantity: '20 ml' },
    ],
    recipe: [
      'Stir ingredients in a mixing glass with ice.',
      'Strain into a chilled Nick and Nora glass. Garnish with a lemon twist.',
    ],
    taste: 'Bitter',
    time: '3 min',
    level: 'Expert',
  },
  {
    id: '907e74b7-8d0b-4259-bbf0-f5974d3554dd',
    name: 'A Royale with Rum',
    description: 'This yummy milkshake twist is the perfect sweet treat…',
    img: 'https://images.unsplash.com/photo-1592284441902-bd5fde3e6f87?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Almond Butter', quantity: '1 scoop(s)' },
      { name: 'Triple Sec Orange Liqueur', quantity: '30 ml' },
      { name: 'Milk', quantity: '120 ml' },
      { name: 'Black rum', quantity: '60 ml' },
      { name: 'Vanilla Ice Cream', quantity: '3 scoop(s)' },
    ],
    recipe: ['Add all ingredients to a high-powered blender and blend to combine.', 'Garnish with an orange peel'],
    taste: 'Creamy',
    time: '3 min',
    level: 'Beginner',
  },
  {
    id: '874c95c1-7abc-4c60-a976-967269ca6175',
    name: 'After Dinner Special',
    description:
      'This cocktail used to be a pousse-café, to be drank layer after layer. But its orange and herbal notes work well when stirred, and served over ice.',
    img: 'https://images.unsplash.com/photo-1527762055594-4956c0c8c617?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Benedictine', quantity: '30 ml' },
      { name: 'Triple Sec Orange Liqueur', quantity: '30 ml' },
      { name: 'MilkYellow Chartreuse', quantity: '30 ml' },
    ],
    recipe: [
      'Combine all ingredients in a chilled mixing glass',
      'Add ice and stir until well-chilled',
      'Strain into a chilled wine glass',
      'Garnish with orange twist',
    ],
    taste: 'Sweet & dry',
    time: '2 min',
    level: 'Beginner',
  },
  {
    id: '9b849118-2d58-43eb-8612-87a58bcc185a',
    name: 'Berry Margarita',
    description:
      'Perfect for the fall season when berries are at their ripest. It produces a beautiful and bright pink color that is seducing even the most shy amateurs',
    img: 'https://images.unsplash.com/photo-1563223771-5fe4038fbfc9?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Blanco tequila', quantity: '45 ml' },
      { name: 'Triple Sec Orange Liqueur', quantity: '30 ml' },
      { name: 'Fresh blackberries', quantity: '4 unit' },
      { name: 'Fresh lime juice', quantity: '20 ml' },
    ],
    recipe: [
      'Combine all ingredients in a cocktail shaker',
      'Add ice and shake until well-chilled',
      'Strain into a chilled Old Fashioned glass',
      'Garnish with a blackberry',
    ],
    taste: 'Sour & fruity',
    time: '3 min',
    level: 'Intermediate',
  },
  {
    id: 'e4bff335-ab72-40be-b43e-717bc0d47d47',
    name: 'Atlas',
    description:
      'This American concoction was published in Chicago in 1937, it has a unique blend of fruits and light woody notes.',
    img: 'https://images.unsplash.com/photo-1602835124432-0ca2d2e66183?q=80&w=1930&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Angostura Bitters', quantity: '1 dash(es)' },
      { name: 'Triple Sec Orange Liqueur', quantity: '20 ml' },
      { name: 'Calvados', quantity: '45 ml' },
      { name: 'Rum', quantity: '20 ml' },
    ],
    recipe: [
      'Combine all ingredients in a chilled mixing glass',
      'Add ice and stir until well-chilled',
      'Strain into a chilled Old Fashioned glass',
      'Garnish with an lemon twist',
    ],
    taste: 'Dry & spicy',
    time: '2 min',
    level: 'Beginner',
  },
  {
    id: '4ab185c9-dd35-4557-ae65-7fc4eb53982d',
    name: 'Blue Bird',
    description: 'Blue Bird was a land speed record that inspired two great bartenders to created a cocktail...',
    img: 'https://images.unsplash.com/photo-1587888559483-c16e80d8dded?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Blue food coloring', quantity: '3 dash(es)' },
      { name: 'Triple Sec Orange Liqueur', quantity: '20 ml' },
      { name: 'Fresh lemon juice', quantity: '15 ml' },
      { name: 'Maraschino', quantity: '3 dash(es)' },
      { name: 'Vodka', quantity: '50 ml' },
    ],
    recipe: [
      'Combine all ingredients in a cocktail shaker',
      'Add ice and shake until well-chilled',
      'Strain into a chilled coupe or cocktail glass',
    ],
    taste: 'Fruity and bitter',
    time: '2 min',
    level: 'Intermediate',
  },
  {
    id: '8e5852ef-f7bc-4c30-8455-35a74e42923e',
    name: 'Breakfast Martini',
    description: 'Invented in 1997 by the internationally acclaimed bartender Salvatore Calabrese...',
    img: 'https://images.unsplash.com/photo-1648231838668-cb196c88f2a5?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Triple Sec Orange Liqueur', quantity: '15 ml' },
      { name: 'Fresh lemon juice', quantity: '15 ml' },
      { name: 'Orange marmalade', quantity: '1 Tbsp(s)' },
      { name: 'Gin', quantity: '50 ml' },
    ],
    recipe: [
      'Combine all ingredients in a cocktail shaker',
      'Add ice and shake until well-chilled',
      'Strain into a chilled coupe or cocktail glass',
      'Garnish with an orange wedge',
    ],
    taste: 'Sour & dry',
    time: '2 min',
    level: 'Intermediate',
  },
  {
    id: '8bc806ad-e08c-4e52-b8a0-2a1a78122757',
    name: 'Coffee Merger',
    description: 'A tasty and refreshing coffee based cocktail...',
    img: 'http://images.unsplash.com/photo-1619503569646-50b2154078ac?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Triple Sec Orange Liqueur', quantity: '25 ml' },
      { name: 'Espresso', quantity: '25 ml' },
      { name: 'liquor', quantity: '30 ml' },
    ],
    recipe: [
      'Combine all ingredients in a cocktail shaker',
      'Add ice and shake until well-chilled',
      'Strain into a chilled coupe or cocktail glass',
    ],
    taste: 'Fresh & bitter',
    time: '2 min',
    level: 'Intermediate',
  },
  {
    id: '7f12f8a2-bab7-476f-85f0-62dcddf44a28',
    name: 'Negroni',
    description: 'A classic Italian cocktail with bitter, sweet, and herbal flavors.',
    img: 'https://plus.unsplash.com/premium_photo-1661403953033-25f180296ad6?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Gin', quantity: '30 ml' },
      { name: 'Campari', quantity: '30 ml' },
      { name: 'Sweet Vermouth', quantity: '30 ml' },
    ],
    recipe: [
      'Add all ingredients into a mixing glass with ice and stir until chilled.',
      'Strain into a rocks glass over a large ice cube.',
      'Garnish with an orange peel.',
    ],
    taste: 'Bitter & herbal',
    time: '2 min',
    level: 'Intermediate',
  },
  {
    id: 'a3d9e3d6-48e5-4c87-9e5c-8f08f1bdfd75',
    name: 'Mojito',
    description: 'A refreshing Cuban highball with mint and lime.',
    img: 'https://images.unsplash.com/photo-1631067451074-27e2826ec83b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'White Rum', quantity: '50 ml' },
      { name: 'Fresh Lime Juice', quantity: '25 ml' },
      { name: 'Sugar', quantity: '2 tsp' },
      { name: 'Mint Leaves', quantity: '8-10 leaves' },
      { name: 'Soda Water', quantity: 'To top' },
    ],
    recipe: [
      'Muddle mint and sugar with lime juice in a glass.',
      'Add rum and fill with ice.',
      'Top with soda and garnish with mint sprig.',
    ],
    taste: 'Fresh & minty',
    time: '3 min',
    level: 'Beginner',
  },
  {
    id: 'fa9c17e2-b109-4c8e-9f3b-9d742212e2bb',
    name: 'Mai Tai',
    description: 'A fruity and complex tiki cocktail packed with rum and citrus.',
    img: 'https://images.unsplash.com/photo-1648757997020-94e698e36e55?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'White Rum', quantity: '30 ml' },
      { name: 'Dark Rum', quantity: '30 ml' },
      { name: 'Orange Curaçao', quantity: '15 ml' },
      { name: 'Lime Juice', quantity: '30 ml' },
      { name: 'Orgeat Syrup', quantity: '15 ml' },
    ],
    recipe: [
      'Shake all ingredients except dark rum with ice.',
      'Strain into a rocks glass filled with crushed ice.',
      'Float dark rum on top. Garnish with mint and lime.',
    ],
    taste: 'Fruity & strong',
    time: '3 min',
    level: 'Intermediate',
  },
  {
    id: '4bc234ee-fb6b-4df3-89e3-5be0e6ffcad6',
    name: 'Whiskey Sour',
    description: 'A simple yet satisfying balance of sweet and sour flavors.',
    img: 'https://plus.unsplash.com/premium_photo-1671647122567-ade48287e971?q=80&w=388&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Bourbon Whiskey', quantity: '50 ml' },
      { name: 'Fresh Lemon Juice', quantity: '25 ml' },
      { name: 'Simple Syrup', quantity: '20 ml' },
      { name: 'Egg White (optional)', quantity: '15 ml' },
    ],
    recipe: [
      'Shake all ingredients dry (no ice), then add ice and shake again.',
      'Strain into an old-fashioned glass with ice.',
      'Garnish with a cherry and orange slice.',
    ],
    taste: 'Sweet & sour',
    time: '3 min',
    level: 'Intermediate',
  },
  {
    id: 'e7a15b2f-5b9b-49c8-8d99-9b243e42d901',
    name: 'Classic Martini',
    description: 'A timeless cocktail known for its crisp and sophisticated flavor.',
    img: 'https://plus.unsplash.com/premium_photo-1668771402085-c9b818194d4d?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    ingredients: [
      { name: 'Gin', quantity: '60 ml' },
      { name: 'Dry vermouth', quantity: '10 ml' },
    ],
    recipe: [
      'Pour gin and dry vermouth into a mixing glass filled with ice.',
      'Stir well for 30 seconds until chilled.',
      'Strain into a chilled martini glass.',
      'Garnish with a lemon twist or an olive.',
    ],
    taste: 'Dry',
    time: '3 min',
    level: 'Intermediate',
  },
];
